language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk13

notifications:
  email: false

sudo: false

git:
  depth: false

cache:
  directories:
    - $HOME/.m2

#delete all our historic build artifacts so that the stale versions do
#not pollute the build.
before_script:
  - rm -Rf $HOME/.m2/repository/org/revapi/classif

script:
  - mvn clean verify --batch-mode --fail-at-end

after_success:
- bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X xcode

