== Classif

image:https://travis-ci.org/revapi/classif.svg?branch=master[Build Status,link=https://travis-ci.org/revapi/classif]

WARNING: This is a work in progress and may eat your kittens. Use at your own risk ;)

A library to sift through java classes using a structural search.

Why would anyone want something like this? Because there are policies on how the code should be organized, what is safe
to use and how, etc. Classif is the first stepping stone for tools that can check such policies. There are tools that
can do similar things with the source code but Classif works on the bytecode level.

=== Examples

NOTE: Up to all of the below examples don't work yet. The grammar for parsing the expressions is ready but
the implementation is not :)

Match anything annotated by annotation `Anno` with attribute `a` equal to `'x'`:
```
@a.Anno(a = 'x') ^;
```

Match anything that is annotated by annotation `Anno` with attribute `a` not equal to `'x'`:
```
@a.Anno(a != 'x') ^;
```

Match anything that is not annotated by `Anno`:
```
!@a.Anno ^;
```

Match any type in the package `P`:
```
type ^P.* {}
```

Match any class (i.e. not an interface, enum or annotation type) that not in the package `P`:
```
class ^!P.* {}
```

Match any interface in package `P` or any subpackage of it:
```
interface ^P.** {}
```

Match any type whose name ends in `Private`:
```
type ^/.*Private/ {}
```

Match anything that (indirectly) uses a class annotated as `@Unstable`:
```
^ uses %c; @Unstable class %c=*;
```

Match any type that is annotated `@Unstable` and is used by something annotated `@Stable`:
```
match %e; @Unstable type %e=*; @Stable * uses %e;
```

Match anything that uses some direct implementation of an interface `Iface`:
```
^ uses %impl; type %impl=* directly implements Iface;
```

Match anything that uses some type that is either itself annotated `@Beta` or extends or implements a type
annotated as `@Beta`:
```
^ uses [%beta | %extendsBeta | %implementsBeta];

@Beta type %beta=* {}

type %extendsBeta=* extends %beta {}

type %implementsBeta=* implements %beta {}
```

Match a method called `m` with any number of parameters that is declared in a class that extends a class declared in the
package `x.y` that extends `java.io.InputStream`. Additionally the class with the method `m` implements an interface
that declares a method `k` with any number of parameters. The method `m` is annotated with an annotation that has
an attribute called `attr` with default value of 3:

```
class * extends %b implements %i {
  @%a
  ^m(**);
}

class %b=x.y.* extends java.io.InputStream {}

interface %i=* {
  k(**);
}

@interface %a {
    int attr() default 3;
}
```
